---
- hosts: localhost
  vars:
   array2: []
   sum: Red
   word: hdfs12
   appendlast: yarn/nm
  tasks:
  - name: uri module
    uri:
      url: https://lamp.local/api/v2/config/
      user: root
      password: redhat
      method: GET
      force_basic_auth: yes
      body_format: json
      validate_certs: False
      return_content: no
    register: output

  - name: append a string
    set_fact:
     new_word: "/{{ word }}/{{ appendlast }}"
  - debug: var=new_word

  - name: Filtering whats required
    set_fact:
      filter_original: "{{ output.json.license_info.subscription_name }}"

  - debug:
      var: filter_original

  - name: Splitting the string
    set_fact: 
     array: "{{ filter_original.split() }}"
  
  - debug:
     var: array
   
  - name: set list of Repositories
    set_fact:
     array2: "{{ array2 }} + [ '{{ sum }}' ]"
  
  - debug:
     var: array2

  - set_fact:
        array: "{{ array | difference(array2) }}"

  - debug: var=array



  
   
 
