---
- hosts: localhost
  gather_facts: yes
  vars:
    size1: []
  tasks:
  - name: check size
    set_fact:
        size1: "{{item.size_available/item.size_total*100}}"
        size2: "{{ size2|default([]) + [item.size_available/item.size_total*100] }}"
        
    with_items: "{{ansible_mounts}}"
    register: sizefacts
#whole print2 and debug and register and size1 can be avoided now
  - name: print2 
    set_fact:
      var1: "{{ item.ansible_facts.size1 }}"
    with_items: "{{ sizefacts.results }}"

# - debug:
#     msg: "{{ansible_mounts | type_debug}}"                                        
#     var: sizefacts | type_debug
#      var: size2 | type_debug
#      var: sizefacts
  - name: xxxx
    debug: 
      var: "{{ item }}"
    with_items: "{{ size2 }}"
